import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './toastify-custom.css';
import { SurveyProvider } from './Provider';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en" className='relative'>
      <SurveyProvider >
        <body className={inter.className} >

          <h2 className='text-center font-bold text-lg fixed top-3 left-0 right-0 pb-1 border-b-2 border-orange-400'>Customer Feedback loop</h2>

          <div className='h-screen flex items-center justify-center'>
            {children}
          </div>
          <ToastContainer />
        </body>
        </SurveyProvider>
    </html>
  )
}
